### ISSUE TITLE
Error while running original code.

### ISSUE THREAD

**Issue by legendarynacar** [derwyddon/linkedin_post_comments_analyzer#1]
I am receiving this. Can you tell me whats wrong?
 
Command: ` python3 linkedin_comment_analyzer.py analyze Comments.html ./output '2018' --debug=yes `

Output:
```bash
Post comments html DOWNLOADED file to analyze:Comments.html
Images profiles will NOT be downloaded
Post comments readed. Processing 195 comments
[########################################################################] 100%
Traceback (most recent call last):
  File "linkedin_comment_analyzer.py", line 331, in <module>
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "linkedin_comment_analyzer.py", line 325, in analyze
    processed_file_path = parse_comments(html_doc, imageoutdir, debug, timedate)
  File "linkedin_comment_analyzer.py", line 280, in parse_comments
    processed_file_path = Path(Path(images_path).parents[1],'comments',timedate_path+'-'+'post_processed.xlsx')
  File "/usr/lib/python3.6/pathlib.py", line 594, in __getitem__
    raise IndexError(idx)
IndexError: 1
```

**Comment by derwyddon** [comment]
I apologize for the delay. I am sure you have found the problem by yourself. I have found the same trouble multiple times with code from other developers that are using a different OS that mine. It is a matter of the pathlib library and the difference between linux and windows paths that are using a different separator ('/' and '\')
